### ISSUE TITLE
Faulty warning message

### ISSUE THREAD

**Issue by Gertian** [carstenbauer/ThreadPinning.jl#106]
Hi,

Im trying this package out and noticed the following.
![image](https://github.com/user-attachments/assets/14451837-e253-46df-9b11-8ed91a48cd74)

I don't this this is a big deal but it's probably desirable to fix this.

**Comment by carstenbauer** [comment]
Mind creating a PR?

**Comment by Gertian** [comment]
Ok I got some deadlines today but I'll do this at the very least next week :)

**Comment by Gertian** [comment]
@carstenbauer, the above PR updates the error message :)
Let me know if you had anything else in mind though.
