### ISSUE TITLE
Allow running bandwidth benchmarks with different kernels

### ISSUE THREAD

**Issue by giordano** [carstenbauer/ThreadPinning.jl#35]
Follow up from https://github.com/giordano/julia-on-fugaku/issues/1: it'd be nice to allow running `bwscaling` (and necessarily also `bwbench`) with kernels other than sdxapy.  This would allow comparing results with https://github.com/RRZE-HPC/TheBandwidthBenchmark, which basically reports scaling all other kernels but sdaxpy:  init, sum, copy, update, triad.  Example: [Fujitsu FX700 S1 M4 C48](https://github.com/RRZE-HPC/TheBandwidthBenchmark/wiki/Fujitsu-FX700-S1-M4-C48).

**Comment by carstenbauer** [comment]
Wrong repository, see https://github.com/JuliaPerf/BandwidthBenchmark.jl/issues/9.
