### ISSUE TITLE
Precompilation failing on FUGAKU

### ISSUE THREAD

**Issue by carstenbauer** [carstenbauer/ThreadPinning.jl#75]
Because of (among other things?) `pinthreads(:numa)`.

**Comment by giordano** [comment]
For the benefit of future readers, the work around is to [disable precompilation](https://julialang.github.io/PrecompileTools.jl/stable/#Package-developers:-reducing-the-cost-of-precompilation-during-development) with PrecompileTools, i.e. in your environment create the file `LocalPreferences.toml` with content
```toml
[ThreadPinning]
precompile_workload = false
```
