### ISSUE TITLE
Feature request: temporary pinning (with do block) ?

### ISSUE THREAD

**Issue by ederag** [carstenbauer/ThreadPinning.jl#81]
`pinthreads`  is able to stabilize benchmark runs inside Pluto too, thanks !
It seems to play well with the new [Pluto/Malt](https://github.com/JuliaPluto/Malt.jl) combination.

Yet it would be nice to encapsulate a block (e.g. a benchmark) inside `pinthreads`,
leaving the rest of the notebook running normally.

For instance, defining
```julia
# `with_pinthreads` instead of just `pinthreads` to avoid piracy
function with_pinthreads(f::Function, args...; kwargs...)
	pinthreads(args...; kwargs...)
	result = f()
	unpinthreads()
	result
end
```
allows
```julia
with_pinthreads([0]) do
	@benchmark sin.(x) setup=(x = rand(10))
end
```

Would that be in the `ThreadPinning` package scope ?
Of course it would be better to store/restore the previous thread pinning (unpinned, `:core`, ...)
instead of just `unpinthreads()`, but I fail to see how to do that.

**Comment by carstenbauer** [comment]
I think that such a feature would be a nice addition.

> Of course it would be better to store/restore the previous thread pinning (unpinned, `:core`, ...)
> instead of just `unpinthreads()`, but I fail to see how to do that.

That's doable. We can simply query and store the affinity mask of each thread at the beginning and then to restore it at the end. (see `ThreadPinning.get_affinity_mask` / `ThreadPinning.uv_thread_getaffinity`)

**Comment by carstenbauer** [comment]
Added in https://github.com/carstenbauer/ThreadPinning.jl/pull/82. Please try it out!

**Comment by ederag** [comment]
#82 works perfectly, tested with `Pluto v0.19.32`,
tried in particular
```julia
unpinthreads()  # outer setup unpinned
with_pinthreads([10]) do
	# runs on the 11th CPU, as expected
	@benchmark sin.(x) setup=(x = rand(10))
end
# runs on a random CPU (tested several times), as expected
@benchmark sin.(x) setup=(x = rand(10))

pinthreads([0])  # outer setup pinned to the first CPU
with_pinthreads([10]) do
	# runs on the 11th CPU, as expected
	@benchmark sin.(x) setup=(x = rand(10))
end
# runs on the first CPU, as expected
@benchmark sin.(x) setup=(x = rand(10))
```
Thanks !

**Comment by carstenbauer** [comment]
Great, I'll tag a new release.

**Comment by carstenbauer** [comment]
BTW, @ederag, if you care about ThreadPinning.jl in Pluto, I always wanted to have nicer support for `threadinfo` in Pluto. I'm thinking of
* native output (not in the terminal look)
* interactively updating (when one changes the pinning with `pinthreads`)

Maybe you want to give that a try? :)

**Comment by ederag** [comment]
Sorry, I'd like to help but I'm not good enough at HTML display stuff.

And I do not see how to get Pluto reactive updates for mutations (see https://github.com/fonsp/Pluto.jl/issues/564).
Actually the operating system might be allowed to move threads, so a periodic polling seems adequate ?
Here is a [Pluto notebook](https://gist.github.com/ederag/ecad5f9c573e88683949de88d25c0ac2) (start the clock to get periodic updates).
![Screenshot_20231114_093446](https://github.com/carstenbauer/ThreadPinning.jl/assets/10962809/6ff44b0f-4b4a-42bd-88e9-05ed86681dfa)



Pluto people on [zulip](https://julialang.zulipchat.com/#narrow/stream/243342-pluto.2Ejl) or [discourse](https://discourse.julialang.org/c/tools/pluto) do amazing things and would probably be more helpful.
