### ISSUE TITLE
Disable warning when pinthreads(:affinitymask) under Slurm

### ISSUE THREAD

**Issue by simonbyrne** [carstenbauer/ThreadPinning.jl#88]
In a slurm job:
```
julia> pinthreads(:affinitymask)
┌ Warning: You seem to be running in a SLURM allocation that doesn't cover the entire node. Most likely, only a subset of the available CPU-threads will be accessible. This might lead to unexpected pinning results.
└ @ ThreadPinning ~/.julia/packages/ThreadPinning/BPm8Z/src/pinning.jl:272
```
From what I understand, `pinthreads(:affinitymask)` should be safe under Slurm (since Slurm sets the affinity itself)

**Comment by carstenbauer** [comment]
@simonbyrne I'm confused, this seems to already be implemented. [We have `warn = false` as the default](https://github.com/carstenbauer/ThreadPinning.jl/blob/main/src/pinning.jl#L157-L158) for `pinthreads(:affinitymask)`. I also just confirmed that there is no warning for `:affinitymask` (there is for other pinning strategies).

Are you perhaps on an old version?

**Comment by carstenbauer** [comment]
I wonder why I didn't tag a new release. Will check and release a new version soon.
