### ISSUE TITLE
pinthreads(:affinitymask) fails with hyperthreads

### ISSUE THREAD

**Issue by KrisJensen** [carstenbauer/ThreadPinning.jl#93]
pinthreads(:affinitymask) fails with error message "More Julia threads than CPU-threads specified by affinity mask" when I have enough threads+hyperthreads but not enough physical cores.

**Comment by carstenbauer** [comment]
I thought about this once more and it isn't clear to me why it's failing. Could you tell me what `ThreadPinning.initial_affinity_mask()` and `threadinfo()` gives on your system / in your SLURM allocation?

**Comment by carstenbauer** [comment]
Closing for now. (Feel free to provide more information.)
